#define SETTINGS_INITCOND_FILE "/tmp/heat/u0.bin"
#define	SETTINGS_SOLUTION_FILE "/tmp/heat/u.bin"

#define SETTINGS_PROBLEM_TYPE Problem3d
#define SETTINGS_NUM_OF_ITERATIONS_TO_SKIP 10
#define SETTINGS_MAXT 1.0
#define SETTINGS_TAU 0.005

#define SETTINGS_DX 1.0
#define SETTINGS_NX 100
#define SETTINGS_BCX0_TYPE 0
#define SETTINGS_BCX1_TYPE 0

#define SETTINGS_DY 1.0
#define SETTINGS_NY 100
#define SETTINGS_BCY0_TYPE 0
#define SETTINGS_BCY1_TYPE 0

#define SETTINGS_DZ 1.0
#define SETTINGS_NZ 100
#define SETTINGS_BCZ0_TYPE 0
#define SETTINGS_BCZ1_TYPE 0